name: Notify Discord of GitHub Activity (`cd-notify-discord` from Continous-Delphi)
#
# -----------------------------------------------------------------------------
# cd-notify-discord
#
# A PowerShell utility to send Discord notifications based on GitHub repository
# activity such as commits, stars, releases, and branch creations
#
# Part of Continuous-Delphi: Focused on strengthening Delphi's continued success
# https://github.com/continuous-delphi
#
# Project repository:
# https://github.com/continuous-delphi/cd-notify-discord
#
# Copyright (c) 2026 Darian Miller
# Licensed under the MIT License.
# https://opensource.org/licenses/MIT
# SPDX-License-Identifier: MIT
# -----------------------------------------------------------------------------
#
on:
  #enable PUSH for commits
  push:

  #enable CREATE for branches/tags
  #create:

  #enable RELEASE for new releases with types of: published
  #release:
  #  types: [published]

  #enable WATCH for stars
  watch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send Discord notification
        shell: pwsh
        env:
          CD_NOTIFY_DISCORD_WEBHOOK_URL:    ${{ secrets.CD_NOTIFY_DISCORD_WEBHOOK_URL }}
          CD_NOTIFY_DISCORD_PUSH_BRANCHES:  ${{ vars.CD_NOTIFY_DISCORD_PUSH_BRANCHES }}
          CD_NOTIFY_DISCORD_CREATE:         ${{ vars.CD_NOTIFY_DISCORD_CREATE }}
          CD_NOTIFY_DISCORD_RELEASE:        ${{ vars.CD_NOTIFY_DISCORD_RELEASE }}
          CD_NOTIFY_DISCORD_STAR:           ${{ vars.CD_NOTIFY_DISCORD_STAR }}
          GITHUB_EVENT_NAME:                ${{ github.event_name }}
          GITHUB_EVENT_PATH:                ${{ github.event_path }}
        run: |
          ./source/cd-notify-discord.ps1
